function(add_idf_include target component)
    if (EXISTS $ENV{IDF_PATH}/components/${component}/include)
        target_include_directories(${target} PRIVATE $ENV{IDF_PATH}/components/${component}/include)
    elseif (EXISTS $ENV{IDF_PATH}/components/${component})
        target_include_directories(${target} PRIVATE $ENV{IDF_PATH}/components/${component})
    else ()
        message(FATAL_ERROR "Given component path does not exist: ${component}")
    endif ()
endfunction()

function(verify_idf_path)
    if (NOT EXISTS "$ENV{IDF_PATH}/Kconfig")
        message(FATAL_ERROR "Environment IDF_PATH must be set to an existing IDF-installation. IDF_PATH: '$ENV{IDF_PATH}'")
    else ()
        message(STATUS "IDF_PATH appears valid.")
    endif ()
endfunction()

function(optionally_enable_idf_project_management)
    if (IDF_PLATFORM)
        message(STATUS "Compiling for IDF, enabling IDF project management.")
        include($ENV{IDF_PATH}/tools/cmake/project.cmake)
    endif ()
endfunction()