function(set_compile_options target)
    target_compile_options(${target} PRIVATE -Werror -Wall -Wextra)
    target_compile_options(${target} PRIVATE $<$<COMPILE_LANGUAGE:CXX>: -Wnon-virtual-dtor>)
    target_compile_options(${target} PRIVATE $<$<COMPILE_LANGUAGE:CXX>: -Wuseless-cast>)
    target_compile_options(${target} PRIVATE -Wcast-align -Wunused )
    target_compile_options(${target} PRIVATE -Wconversion -Wsign-conversion)
    target_compile_options(${target} PRIVATE -Wlogical-op -Wdouble-promotion -Wformat=2)

    if( NOT ESP_PLATFORM )
        target_compile_options(${target} PRIVATE -Wmisleading-indentation -Wduplicated-cond -Wduplicated-branches -Wnull-dereference)
        target_compile_options(${target} PRIVATE -fsanitize=address -fno-omit-frame-pointer -fsanitize-address-use-after-scope)
    endif()
endfunction()