function(smooth_verify_idf_path)
    if (NOT EXISTS "$ENV{IDF_PATH}/Kconfig")
        message(FATAL_ERROR "Environment IDF_PATH must be set to an existing IDF-installation. IDF_PATH: '$ENV{IDF_PATH}'")
    else ()
        message(STATUS "IDF_PATH appears valid.")
    endif ()
endfunction()

function(smooth_configure_link)
    if(${CMAKE_CXX_COMPILER} MATCHES "xtensa")
        message(STATUS "Smooth: Importing IDF components.")

        set(IDF_EXTRA_COMPONENT_DIRS "${IDF_EXTRA_COMPONENT_DIRS} ${CMAKE_CURRENT_LIST_DIR}/smooth_idf_component")
        include($ENV{IDF_PATH}/tools/cmake/idf_functions.cmake)
        idf_import_components(components $ENV{IDF_PATH} esp-idf)
        idf_link_components(${PROJECT_NAME} "${components}")
    else()
        message(STATUS "Smooth: Building for native Linux.")

        message(STATUS "Compiling for native Linux: Using default values for Smooth-MQTT")
        add_definitions("-DCONFIG_SMOOTH_MAX_MQTT_MESSAGE_SIZE=3500")
        add_definitions("-DCONFIG_SMOOTH_MAX_MQTT_OUTGOING_MESSAGES=10")
        add_definitions("-DCONFIG_SMOOTH_MQTT_LOGGING_LEVEL=0")
    endif()
endfunction()