name: C/C++ CI

on: [push, pull_request]

jobs:
  CI:
    runs-on: ubuntu-latest
    
    # This job can be run locally through CI/main.sh

    steps:
    - uses: actions/checkout@v1
    - name: Get submodules
      run: git submodule update --init --checkout --recursive
    - name: Build and test
      run: |
        ./CI/main.sh
    Formatting:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - name: Check formatting
        run: |
          docker run --rm --mount type=bind,source="($pwd)",target="/cfg" --mount type=bind,source="$(pwd)/lib",target="/src" permalmberg/uncrustify:latest
          docker run --rm --mount type=bind,source="($pwd)",target="/cfg" --mount type=bind,source="$(pwd)/test",target="/src" permalmberg/uncrustify:latest
          docker run --rm --mount type=bind,source="($pwd)",target="/cfg" --mount type=bind,source="$(pwd)/mock-idf",target="/src" permalmberg/uncrustify:latest