name: C/C++ CI

on: pull_request

jobs:
  CI:
    runs-on: ubuntu-latest
    
    # This job can be run locally through CI/main.sh

    steps:
    - uses: actions/checkout@v1
    - name: Get submodules
      run: git submodule update --init --checkout --recursive
    - name: Build and test on host platform
      run: |
        docker run -u `id -u` --rm --mount type=bind,source="$(pwd)",target=/src --workdir /src docker.pkg.github.com/permalmberg/smooth/build:latest /src/CI/container_scripts/build_smooth_host.sh
        docker run -u `id -u` --rm --mount type=bind,source="$(pwd)",target=/src --workdir /src/build/test/unit_tests docker.pkg.github.com/permalmberg/smooth/build:latest ./unit_test
    - name: Build for ESP32 platform
      run: |
        docker run -u `id -u` --rm --mount type=bind,source="$(pwd)",target=/src --workdir /src docker.pkg.github.com/permalmberg/smooth/build:latest /src/CI/container_scripts/build_smooth_esp32.sh

