name: C/C++ CI

on: [push, pull_request]

jobs:
  CI_host:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: true
    - name: Build
      run: docker-compose run --rm host ./CI/build_smooth_host.sh
    - name: Test
      run: docker-compose run --rm -w /src/build_host/test/linux_unit_tests host ./linux_unit_tests
  
  CI_esp:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        esp_idf_version:
          - 'latest'
          - 'release-v4.3'
          - 'release-v4.2'
    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: true
    - name: Build
      run: docker-compose run --rm esp32 ./CI/build_smooth_esp32.sh
      env:
          ESP_IDF_VERSION: ${{ matrix.esp_idf_version }}

  Formatting-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check formatting
      run: |
        ./CI/check_formatting.sh
