name: C/C++ CI

on: [pull_request]

jobs:
  CI:
    # This job can be run locally through ./CI/main.sh
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get submodules
      run: git submodule update --init --checkout --recursive
    - name: Build and test
      run: |
        ./CI/build_test.sh
  Formatting-check:
    # This job can be run locally through ./CI/check_formatting.sh
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check formatting
      run: |
        ./CI/check_formatting.sh
