name: C/C++ CI

on: pull_request

jobs:
  CI:
    runs-on: ubuntu-latest
    
    # This job can be run locally through CI/main.sh

    steps:
    - uses: actions/checkout@v1
    - name: Get submodules
      run: git submodule update --init --checkout --recursive
    - name: Build and test
      run: |
        ./CI/main.sh
